name: Check lfs

on:
  pull_request:
    branches:
      - 'master'

jobs:
  check-lfs:
    runs-on: [ ubuntu-slim ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          lfs: false
      - name: validate lfs
        run: git lfs fsck --pointers
